site_name: 清气养人

theme:
  name: material
  logo: image/icon.jpeg
  icon:
    admonition:
      question: octicons/question-16
  features:
    - navigation.path
  palette:
    primary: indigo
  language: zh

nav:
  - 首页: index.md
  - 走进清华: tsinghua.md
  - 专业介绍:
    - 为先书院: 专业介绍/为先书院.md
    - 电子信息类: 专业介绍/电子信息类.md
    - 机械、航空与动力类: 专业介绍/机械、航空与动力类.md
    - 计算机类: 专业介绍/计算机类.md
    - 经济、金融与管理类: 专业介绍/经济、金融与管理类.md
    - 强基计划: 专业介绍/强基计划.md
    - 协和医学院: 专业介绍/协和医学院.md
  - 学习方法分享:
    - 语文: 学习方法分享/study.md
  - 问答墙:
    - 2022: 问答墙/2022.md
    - 2023: 问答墙/2023.md
  # - 新生入学指南: 新生入学指南.md
  - 其他高校宣讲: others.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tilde

plugins:
  - glightbox